<template>
  <div class="box">
     <img @click="timeOut()" class="image slide-in-right" :src="images[current]" alt="">
  </div>
 
  <button style="position: absolute;left: 9px;
  top: 500px;" @click="plus(current)">-</button>
  <button style="position: absolute; right: 9px; top: 500px" @click="minus(current)">+</button>
  <div v-if="this.current === 0" class="textBox">
    <h1 class="text">ЗАПЧАСТИ НА ОТЕЧЕСТВЕННЫХ ГИГАНТОВ КАМАЗ, МАЗ, ГАЗ</h1>
    <p class="microtext">ГАЗель, ГАЗон-NEXT, <br>
  ВАЛДАЙ, МТЗ, спецтехники и <br>
  сельхозтехники</p>
  </div>
  <div v-if="this.current === 1" class="textBox">
    <h1 class="text">ТЕХНИЧЕСКИЕ ЖИДКОСТИ , СМАЗОЧНЫЕ МАТЕРИАЛЫ и АКБ</h1>
  </div>
  <div v-if="this.current === 2" class="textBox">
    <h1 class="text">АКСЕССУАРЫ НА ЛЮБОЙ ВКУС И ЦВЕТ</h1>
  </div>
  <div v-if="this.current === 3" class="textBox">
    <h1 class="text">ЛУЧШИЕ ЗАПЧАСТИ НА ПЛАНЕТЕ</h1>
  </div>
</template>

<script>
import img1 from '@/assets/img/ГРУЗИЩЕ.jpg'
import img2 from '@/assets/img/газон некст.jpg'
import img3 from '@/assets/img/камаз.jpeg'
import img4 from '@/assets/img/краз.jpg'

export default {
  data: function () {
    return {
      current: 0,
      images: [
        img1,
        img2,
        img3,
        img4,

      ]
    }
  },
  methods: {
    plus(current) {
      if (current === 3) {
        this.current = 0;
      }
      else {
        this.current += 1;
      }
    },
    minus(current) {
      if (current === 0) {

        this.current = 3;
      }
      else {
        this.current -= 1;
      }
    },
    timeOut() {
      setTimeout(() => {
        this.plus(this.current);
        this.timeOut();
      }, 3000);
    },
    printText() {
      switch (this.current) {
        case current === 0:

          break;

        default:
          break;
      }
    }
  },
  beforeMount() {
    this.timeOut();
  },
}



</script>

<style scoped>
/* ----------------------------------------------
 * Generated by Animista on 2023-12-30 20:45:33
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation slide-in-right
 * ----------------------------------------
 */
.slide-in-right {
  -webkit-animation: slide-in-right 0.5s cubic-bezier(0.250, 0.460, 0.450, 0.940) both;
  animation: slide-in-right 0.5s cubic-bezier(0.250, 0.460, 0.450, 0.940) both;
}

@-webkit-keyframes slide-in-right {
  0% {
    -webkit-transform: translateX(1000px);
    transform: translateX(1000px);
    opacity: 0;
  }

  100% {
    -webkit-transform: translateX(0);
    transform: translateX(0);
    opacity: 1;
  }
}

@keyframes slide-in-right {
  0% {
    -webkit-transform: translateX(1000px);
    transform: translateX(1000px);
    opacity: 0;
  }

  100% {
    -webkit-transform: translateX(0);
    transform: translateX(0);
    opacity: 1;
  }
}

.image {
  height: 90vh;
  object-fit: cover;
  width: 100%;
  background-color: rgba(200,100,0,.5);
  background-blend-mode: multiply;
    background-size: cover;
  background-image: url('https://placehold.co/300');

}
.textBox{
  width: 100%;
  display: flex;
  position: absolute;
  justify-content: center;
  align-items: center;
  align-content: center;
  flex-direction: column;
  top: 500px;


}
.text{
  font-size: 40px;
  font-weight: bold;
  display: flex;
  justify-content: center;
  color: #fff;
  font-family: Arial;
}
.box {

  background-size: cover;
  background-image: url('https://placehold.co/300');

}
.microtext{
  font-family: Arial;
  font-size: 20px;
  font-weight: bold;
  justify-content: center;
  color: #fff;
  align-items: center;
  align-content: center;
  text-align: center;
}
@media only screen and (max-width: 576px) {
  .text{
    text-align: center;
    justify-content: center;
  }
}
@media only screen and (max-width: 1090px) {
  .text{
    text-align: center;
    justify-content: center;
  }
}
</style>
